"""empty message

Revision ID: 430430ebe799
Revises: 00b85a9c00cc
Create Date: 2024-10-26 10:16:10.428464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430430ebe799'
down_revision = '00b85a9c00cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation')
    # ### end Alembic commands ###
